version: '3.9'

volumes:
  node_modules:

services:
  node:
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    container_name: pokemonote
    working_dir: /pokemonote
    ports:
      - 3000:3000
    volumes:
      - .:/pokemonote
      - node_modules:/pokemonote/node_modules
    environment:
      IS_CONTAINER: 'true'
    stdin_open: true
    tty: true
