name: 'npm ci'
description: 'install packages'
runs:
  using: 'composite'
  steps:
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-next-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: ${{ runner.os }}-next-npm-

    - name: npm ci
      run: npm ci
      shell: bash
