import type { components, paths } from './autoGenerated'

export type Schema<T extends keyof components['schemas']> =
  components['schemas'][T]

export type Response<
  Path extends keyof paths,
  Method extends keyof paths[Path],
  Status extends keyof paths[Path][Method]['responses'] = Method extends 'post'
    ? 201
    : 200,
> = paths[Path][Method]['responses'][Status]['content']['application/json']

export type RequestBody<
  Path extends keyof paths,
  Method extends keyof paths[Path],
> = paths[Path][Method]['requestBody']['content']['application/json']

export type PathParameters<
  Path extends keyof paths,
  Method extends keyof paths[Path],
> = paths[Path][Method]['parameters']['path']
