import type { components, paths } from './autoGenerated'

export type Schema<T extends keyof components['schemas']> =
  components['schemas'][T]

export type UrlPaths = keyof paths

export type HttpMethod = {
  [K in keyof paths]: keyof paths[K]
}[keyof paths]

export type Response<
  Path extends keyof paths,
  Method extends keyof paths[Path],
  Status extends keyof paths[Path][Method]['responses'] = 200
> = paths[Path][Method]['responses'][Status]['content']['application/json']

export type RequestBody<
  Path extends keyof paths,
  Method extends keyof paths[Path]
> = paths[Path][Method]['requestBody']['content']['application/json']

export type AxiosConfigWrapper<
  Path extends keyof paths,
  Method extends keyof paths[Path]
> = {
  url: Path
  method: Method
  data?: RequestBody<Path, Method>
}
