[[redirects]]
  from = "/email/verify/:id"
  to = "/email/verify/[id].html"
  status = 200
  force = true

[[redirects]]
  from = "/password/verify/:id"
  to = "/password/verify/[id].html"
  status = 200
  force = true
