import useSWR from 'swr'
import type { paths } from '@/types/openapi/autoGenerated'
import type { Response } from '@/types/openapi/extractor'
import type { SWRConfiguration } from 'swr'

export const useOpenApiSWR = <
  T extends {
    [K in keyof paths]: 'get' extends keyof paths[K] ? K : never
  }[keyof paths],
>(
  url: T,
  options?: SWRConfiguration
) => {
  return useSWR<Response<T, 'get'>>(url, options)
}
