name: test_build_deploy
on: push

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:18.16.0

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: npm install
  #       uses: ./.github/actions/test_build_deploy

  #     - name: Test
  #       run: npm run test

  build:
    runs-on: ubuntu-latest
    container:
      image: node:18.16.0
    if: github.ref_name == 'main' || github.ref_name == 'develop'
    # needs: test
    steps:
      - uses: actions/checkout@v3

      - name: npm install
        uses: ./.github/actions/test_build_deploy

      - name: delete SEO files
        if: github.ref_name != 'main'
        run: |
          rm -f ./public/robots.txt ./public/sitemap.xml && \
          echo "User-agent: *\nDisallow: /\n" > ./public/robots.txt

      - name: npm run build
        run: npm run build
        env:
          NEXT_PUBLIC_ANALYTICS_ID: ${{ secrets.ANALYTICS_ID }}
          NEXT_PUBLIC_BASE_URL: ${{ github.ref_name == 'main' && secrets.PROD_BASE_URL || secrets.DEV_BASE_URL }}
          NEXT_PUBLIC_NODE_ENV: ${{ github.ref_name == 'main' && 'production' || 'develop' }}
          NEXT_PUBLIC_PAYJP_PUBLIC_KEY: ${{ secrets.PAYJP_PUBLIC_KEY }}

      - name: Upload Directory
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: out
          retention-days: 3

  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' || github.ref_name == 'develop'
    needs: build
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: out
          path: ./out-dir
      - name: Deploy to XSERVER
        run: |
          echo "${{ secrets.XSERVER_PRIVATE_KEY }}" > x-server.key
          chmod 600 x-server.key
          EXCLUDED_DIRECTORIES=$(echo "${{ secrets.EXCLUDED_DIRECTORIES }}")
          for dir in $EXCLUDED_DIRECTORIES
          do
            EXCLUDED_FILTERS+="--filter='P $dir/' "
          done
          echo "Exclude command: $EXCLUDED_FILTERS"
          rsync -avz --delete --delete-delay --delay-updates --filter='P .htaccess' $EXCLUDED_FILTERS -e "ssh -o StrictHostKeyChecking=no -i x-server.key -p 10022" ./out-dir/ ${{ secrets.XSERVER_USER }}@${{ secrets.XSERVER_HOST }}:${{ secrets.DEVELOPMENT_DIRECTORY }}
